// export const CHANGE_CURRENT_SONG='CHANGE_CURRENT_SONG';
export const CHANGE_CURRENT_SONG_DETAIL='CHANGE_CURRENT_SONG_DETAIL';
export const CHANGE_PLAYLIST='CHANGE_PLAYLIST'
export const CHANGE_PLAY_MODE='CHANGE_PLAY_MODE'
export const CHANGE_DISPLAY_SONG_DETAIL='CHANGE_DISPLAY_SONG_DETAIL'
export const CHANGE_DISPLAY_SONG_LYRIC='CHANGE_DISPLAY_SONG_LYRIC'
export const CHANGE_PLAYING_SONG_LYRIC='CHANGE_PLAYING_SONG_LYRIC'
export const CURRENT_PLAY_INDEX='CURRENT_PLAY_INDEX'
