export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS"
export const CHANGE_HOT_RECOMMEND_TITLE='CHANGE_HOT_RECOMMEND_TITLE'
export const CHANGE_HOT_REACOMEND='CHANGE_HOT_REACOMEND'
export const CHANGE_NEW_DISC='CHANGE_NEW_DISC'
export const PUSH_REACOMMEND_TOP_LIST='PUSH_REACOMMEND_TOP_LIST'